/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 19
   Tile set      : C:\Users\ragha\Documents\GitHub\GameBoyShenanigans\Backgrounds\sprites\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 40
#define BackgroundMapHeight 19
#define BackgroundMapBank 0

extern unsigned char BackgroundMap[];

/* End of BACKGROUNDMAP.H */
